import random

used_questions = []

GeneralQuestions = {
    "aaa": "What is the most 'main character' moment you've ever had?",
    "aab": "If you were a ghost, what minor thing would you do to mildly inconvenience people?",
    "aac": "What is an 'unwritten rule' of the internet that everyone should know?",
    "aad": "If you had to change your name to an object in the room with you, what would it be?",
    "aae": "What is a food that everyone seems to love but you secretly think is overrated?",
    "aaf": "If you could add a 13th month to the calendar, what would you call it?",
    "aag": "What is the weirdest dream you still remember clearly?",
    "aah": "You're opening a bar—what is the theme and what is the signature drink called?",
    "aai": "What is a hill you are willing to die on?",
    "aaj": "If humans had 'patch notes,' what bug would you want fixed in the next update?",
    "aak": "What's the most suspicious thing you could be carrying in a violin case?",
    "aal": "If you were a pro-wrestler, what would your entrance theme song be?",
    "aam": "What is a 'useless' talent you have that you're actually proud of?",
    "aan": "What's the worst advice you've ever actually followed?",
    "aao": "If you could live in any fictional world, but only as a background NPC, where would you go?",
    "aap": "What is a common thing that you have never done in your life?",
    "aaq": "If you were a flavor of ice cream, what would you be and why?",
    "aar": "What is the best 'bad' movie you've ever seen?",
    "aas": "If you had to give a 20-minute presentation with zero preparation, what topic are you choosing?",
    "aat": "What is the most 'clutch' moment you've ever had in a game?",
    "aau": "If you could talk to one species of animal, which would it be?",
    "aav": "What is the most outdated piece of technology you still use?",
    "aaw": "What's a trend you hope never comes back?",
    "aax": "If you could have any mythical creature as a pet, what would it be?",
    "aay": "What's the first thing you'd do in a zombie apocalypse?",
    "aaz": "What is your 'comfort' video game or movie?",
    "aba": "If you were a supervillain, what would be your petty origin story?",
    "abb": "What's a hobby you've always wanted to start but never have?",
    "abc": "What is the most unique thing about the city/town you live in?",
    "abd": "What is a scent that brings back a specific memory for you?",
    "abe": "If you could win an Olympic gold medal for any non-sport activity, what would it be?",
    "abf": "What is the most '90s' or '00s' thing you can think of?",
    "abg": "If you could swap lives with a celebrity for one day, who would it be?",
    "abh": "What is your go-to karaoke song?",
    "abi": "If you were a brand, what would your slogan be?",
    "abj": "What is the most expensive thing you've ever broken?",
    "abk": "If you could re-experience one game for the first time again, which one?",
    "abl": "What's the weirdest food combination you actually enjoy?",
    "abm": "What is a word that you always struggle to spell correctly?",
    "abn": "If you could have a dinner party with three people, dead or alive, who are they?",
    "abo": "What is the most 'adult' thing you've had to do recently?",
    "abp": "What is your favorite 'hidden gem' on the internet?",
    "abq": "If you could instantly be fluent in any language, which would you pick?",
    "abr": "What is the most awkward social situation you've ever survived?",
    "abs": "If you were a character in a horror movie, would you be the first to go or the survivor?",
    "abt": "What is the best prank you've ever pulled (or seen pulled)?",
    "abu": "What is something you thought was cool when you were a kid, but isn't now?",
    "abv": "If you could change the color of the sky, what color would it be?",
    "abw": "What is your favorite Wikipedia rabbit hole?",
    "abx": "If you could mute one person in real life, who would it be?",
    "aby": "What is a 'useless' fact that you will never forget?",
    "abz": "If you were a ghost, which celebrity would you choose to haunt?",
    "aca": "What is the most 'out of character' thing you've ever done?",
    "acb": "If you could eliminate one mildly annoying thing from existence (like mosquitos or slow Wi-Fi), what would it be?",
    "acc": "What is the best 'accidental' discovery you've ever made?",
    "acd": "If you could have any fictional character as a roommate, who would it be?",
    "ace": "What's the most ridiculous thing you've seen someone do in public?",
    "acf": "If you had to survive on a deserted island with only one person from this server, who would it be?",
    "acg": "What is your 'guilty pleasure' song that you'd never admit to liking?",
    "ach": "If you could add one illegal thing to the 'legal' list, what would it be?"
}

PressTheButton = {
    "baa": "Would you press the button? You get $10M, but you can only sleep in 2-hour increments.",
    "bab": "Would you press the button? You become the best at your favorite game, but you can never play any other game again.",
    "bac": "Would you press the button? You can teleport, but only to places you've previously cried in.",
    "bad": "Would you press the button? You never have to pay for food again, but everything tastes like cardboard.",
    "bae": "Would you press the button? You can read minds, but only when people are thinking about something gross.",
    "baf": "Would you press the button? You get your dream job, but your boss is your most hated fictional character.",
    "bag": "Would you press the button? You gain 1 trillion dollars, but you turn into a femboy/tomboy permanently.",
    "bah": "Would you press the button? You can freeze time, but you age 2x faster while time is frozen.",
    "bai": "Would you press the button? You never need to sleep, but you have to spend 8 hours a day staring at a wall.",
    "baj": "Would you press the button? You can fly, but only at the speed of a brisk walk.",
    "bak": "Would you press the button? You can talk to animals, but they all think you're an idiot.",
    "bal": "Would you press the button? Every time you sneeze, a random $100 bill appears in your pocket, but you sneeze 50x a day.",
    "bam": "Would you press the button? You are immune to all diseases, but you are constantly slightly itchy.",
    "ban": "Would you press the button? You can see 5 seconds into the future, but you have to narrate everything you see out loud.",
    "bao": "Would you press the button? You have infinite battery on all devices, but you can never use Wi-Fi again.",
    "bap": "Would you press the button? You become a famous influencer, but your parents see every single DM you receive.",
    "baq": "Would you press the button? You can change your physical appearance at will, but only once a year.",
    "bar": "Would you press the button? You always find a parking spot, but you can only drive a neon pink minivan.",
    "bas": "Would you press the button? You can speak every language, but only while yelling.",
    "bat": "Would you press the button? You get a 'Undo' button for real life, but it costs $1,000 per use.",
    "bau": "Would you press the button? You are the funniest person in the room, but you can never laugh at your own jokes.",
    "bav": "Would you press the button? You win every argument, but everyone ends up hating you for it.",
    "baw": "Would you press the button? You get a pet dragon, but it eats $500 worth of meat every day.",
    "bax": "Would you press the button? You can transform into any animal, but you have to eat their diet (bugs, raw meat, etc).",
    "bay": "Would you press the button? You have perfect 20/20 vision, but you see everyone without their clothes (censored).",
    "baz": "Would you press the button? You are never stuck in traffic again, but you have to bike everywhere.",
    "bba": "Would you press the button? You can make anyone fall in love with you, but they become extremely clingy.",
    "bbb": "Would you press the button? You become a genius, but your social skills drop to zero.",
    "bbc": "Would you press the button? You can visit any time period for 1 hour, but you can't bring anything back.",
    "bbd": "Would you press the button? You can eat whatever you want without gaining weight, but you smell like onions.",
    "bbe": "Would you press the button? You get to live in your favorite game, but if you die there, you die for real.",
    "bbf": "Would you press the button? You gain the power of invisibility, but only when you are screaming.",
    "bbg": "Would you press the button? You find $20 on the ground every day, but you have to kick a mailbox to get it.",
    "bbh": "Would you press the button? You get an extra 5 hours in your day, but you have to spend them doing chores.",
    "bbi": "Would you press the button? You can summon any food instantly, but it's always slightly too cold.",
    "bbj": "Would you press the button? You can breathe underwater, but you can no longer breathe air.",
    "bbk": "Would you press the button? You get a HUD like a video game, but it's full of annoying pop-up ads.",
    "bbl": "Would you press the button? You can grow/shrink your height at will, but your clothes don't change size.",
    "bbm": "Would you press the button? You have the perfect singing voice, but you can only sing nursery rhymes.",
    "bbn": "Would you press the button? You can teleport, but you lose a random item of clothing every time.",
    "bbo": "Would you press the button? You are the best cook in the world, but you can't eat your own food.",
    "bbp": "Would you press the button? You can skip any conversation, but the other person knows you skipped it.",
    "bbq": "Would you press the button? You never have to shower again (you stay clean), but you always look damp.",
    "bbr": "Would you press the button? You can talk to your past self, but only for 10 seconds a year.",
    "bbs": "Would you press the button? You get $50,000 right now, but your internet speed is capped at 1mbps forever.",
    "bbt": "Would you press the button? You gain super strength, but you break everything you touch accidentally.",
    "bbu": "Would you press the button? You can spawn a clones of yourself, but they are all incredibly lazy.",
    "bbv": "Would you press the button? You know the answer to every question, but you can't speak or write—only draw.",
    "bbw": "Would you press the button? You get a personal theme song that plays wherever you go, but you can't control the volume.",
    "bbx": "Would you press the button? You can control fire, but you're always shivering cold.",
    "bby": "Would you press the button? You get $1M every time you slap a stranger, but they never know why you did it.",
    "bbz": "Would you press the button? You can talk to your future self, but every time you do, you lose a random memory from your past.",
    "bca": "Would you press the button? You never have to sleep again, but you can only eat raw vegetables.",
    "bcb": "Would you press the button? You can see everyone's 'crush' above their head, but they can see yours too.",
    "bcc": "Would you press the button? You become an Olympic athlete, but you have to wear a full-body chicken suit during every competition.",
    "bcd": "Would you press the button? You get $5M, but you can never use a smartphone again (flip phones only).",
    "bce": "Would you press the button? You can teleport anywhere, but you arrive completely naked every time.",
    "bcf": "Would you press the button? You can pause the world for 1 hour a day, but you have to do a Fortnite dance to activate it.",
    "bcg": "Would you press the button? You can summon any item under $20 instantly, but it always appears in someone else's pocket first.",
    "bch": "Would you press the button? You get your dream car for free, but the horn plays a loud, wet fart sound every time you brake."
}

ReflectionQuestions = {
    "caa": "What is something you've done that your younger self would be proud of?",
    "cab": "If you could change one decision you made in the last year, what would it be?",
    "cac": "What is a 'childish' thing you still enjoy doing?",
    "cad": "What is the most important lesson a mistake has ever taught you?",
    "cae": "How has your taste in music/games changed over the last 5 years?",
    "caf": "What is a personality trait you've worked hard to improve?",
    "cag": "What does 'success' mean to you personally?",
    "cah": "If you could tell your 13-year-old self one thing, what would it be?",
    "cai": "What is a compliment you received that you'll never forget?",
    "caj": "What is something you're currently working on (mentally or physically)?",
    "cak": "What is your favorite memory from this Discord server so far?",
    "cal": "What is one thing you want to accomplish before the year ends?",
    "cam": "What is a fear you have successfully overcome?",
    "can": "Who is someone in your life who has had the biggest impact on you?",
    "cao": "What is something you used to take for granted but now appreciate?",
    "cap": "If you could go back and re-live one day of your life, which would it be?",
    "caq": "What is a habit you're trying to break?",
    "car": "How do you handle stress or burnout?",
    "cas": "What is something you're looking forward to in the next month?",
    "cat": "What is a hobby that makes you forget about your phone?",
    "cau": "What is the best piece of advice you've ever received?",
    "cav": "What is a dream you've had to let go of?",
    "caw": "What is something that always makes you feel like 'you'?",
    "cax": "How do you want to be remembered?",
    "cay": "What is the most 'you' item you own?",
    "caz": "What is a difficult truth you've had to accept about yourself?",
    "cba": "What are you most grateful for today?",
    "cbb": "What is a risk you took that actually paid off?",
    "cbc": "What is something you've forgiven yourself for recently?",
    "cbd": "What is a belief you held strongly that has since changed?",
    "cbe": "What is the most meaningful gift you've ever given or received?",
    "cbf": "What is one thing you would never change about yourself?",
    "cbg": "What makes you feel the most at peace?",
    "cbh": "What is a goal you hit that didn't feel as good as you thought it would?",
    "cbi": "What is a 'small win' you had this week?",
    "cbj": "What is something you're proud of that nobody knows about?",
    "cbk": "What is the biggest life change you've ever experienced?",
    "cbl": "What is a book, movie, or game that changed the way you think?",
    "cbm": "If you could see a statistic of your life (e.g., total steps), what would it be?",
    "cbn": "What do you do when you feel lonely?",
    "cbo": "What is something you wish you started doing sooner?",
    "cbp": "What is your favorite way to spend a day alone?",
    "cbq": "What is a question you wish people would ask you more often?",
    "cbr": "What are you holding onto that you should probably let go of?",
    "cbs": "What does your 'dream life' look like in 10 years?",
    "cbt": "What is a quality you admire most in other people?",
    "cbu": "What is something you've learned about yourself recently?",
    "cbv": "How do you want to grow in the next year?",
    "cbw": "What is the bravest thing you've ever done?",
    "cbx": "What is your favorite thing about your current life?",
    "cby": "What is a piece of media (book/movie/game) that genuinely changed your worldview?",
    "cbz": "If you could see a chart of any 'hidden' stat in your life, what would it be?",
    "cca": "What is something you used to be embarrassed about but are now proud of?",
    "ccb": "What is the most selfless thing you've ever done for someone else?",
    "ccc": "If you could change one personality trait of yours instantly, what would it be?",
    "ccd": "What is the most significant 'butterfly effect' moment in your life?",
    "cce": "What does your 'safe space' look like, whether real or imaginary?",
    "ccf": "What is a 'hard truth' you think more people need to hear?",
    "ccg": "How have your priorities shifted since this time last year?",
    "cch": "What is one thing you've forgiven someone else for that they don't know about?"
}

WouldYouRather = {
    "daa": "What would you rather? Always have to shout when you speak or always have to whisper?",
    "dab": "What would you rather? Be able to talk to animals or speak every human language?",
    "dac": "What would you rather? Date a Goth Femboy or a Hello Kitty Girl?",
    "dad": "What would you rather? Fight 100 chicken-sized zombies or 10 zombie-sized chickens?",
    "dae": "What would you rather? Have a rewind button for your life or a pause button?",
    "daf": "What would you rather? Always be 10 minutes late or 20 minutes early?",
    "dag": "What would you rather? Have no internet for a month or no heating/AC for a month?",
    "dah": "What would you rather? Be able to fly but only 1 foot off the ground or run 100mph but only backwards?",
    "dai": "What would you rather? Live in a world with magic but no technology, or technology but no magic?",
    "daj": "What would you rather? Always have wet socks or always have an itchy throat?",
    "dak": "What would you rather? Only be able to use Discord or only be able to use YouTube?",
    "dal": "What would you rather? Have a tail that wags when you're happy or horns that grow when you're mad?",
    "dam": "What would you rather? Find true love or find $10 million?",
    "dan": "What would you rather? Be the smartest person in a dumb world or the dumbest person in a smart world?",
    "dao": "What would you rather? Lose all your old memories or never be able to make new ones?",
    "dap": "What would you rather? Have to announce every time you have to go to the bathroom or never use the bathroom again but feel like you have to 24/7?",
    "daq": "What would you rather? Be a famous actor or a famous musician?",
    "dar": "What would you rather? Always have a pebble in your shoe or always have a hair in your eye?",
    "das": "What would you rather? Live in the ocean or live in space?",
    "dat": "What would you rather? Have every movie spoiled for you or never be able to see the ending of a movie?",
    "dau": "What would you rather? Only be able to eat spicy food or only be able to eat sweet food?",
    "dav": "What would you rather? Have a 1-minute conversation with your future self or your past self?",
    "daw": "What would you rather? Always be slightly too hot or always be slightly too cold?",
    "dax": "What would you rather? Have cat ears or a dog tail?",
    "day": "What would you rather? Be able to teleport but only to places you can see or be able to go invisible but only when holding your breath?",
    "daz": "What would you rather? Fight a bear with a sword or fight a shark with your bare hands in water?",
    "dba": "What would you rather? Have to listen to the same song forever or never listen to music again?",
    "dbb": "What would you rather? Be able to control fire or control ice?",
    "dbc": "What would you rather? Have a personal chef or a personal driver?",
    "dbd": "What would you rather? Always smell like popcorn or always smell like old books?",
    "dbe": "What would you rather? Be an elf or a dwarf in a fantasy world?",
    "dbf": "What would you rather? Have infinite money but no friends or be poor with the best friends ever?",
    "dbg": "What would you rather? Be able to read minds or be able to see the future?",
    "dbh": "What would you rather? Only be able to wear neon colors or only be able to wear all-white?",
    "dbi": "What would you rather? Have a permanent unfixable bedhead or have to wear a clown nose every day?",
    "dbj": "What would you rather? Always have to rhyme when you speak or always have to sing when you speak?",
    "dbk": "What would you rather? Be able to breathe underwater or be immune to fire?",
    "dbl": "What would you rather? Live in a permanent winter or a permanent summer?",
    "dbm": "What would you rather? Have a heads-up display (HUD) in real life or a save/load state system?",
    "dbn": "What would you rather? Be a vampire or a werewolf?",
    "dbo": "What would you rather? Have to eat a bowl of spiders or a bowl of 100-year-old eggs?",
    "dbp": "What would you rather? Be the first person on Mars or the first person to discover an alien?",
    "dbq": "What would you rather? Have 4 arms or 4 legs?",
    "dbr": "What would you rather? Always have to jump instead of walking or crawl instead of running?",
    "dbs": "What would you rather? Have a bottomless bag or a self-cleaning house?",
    "dbt": "What would you rather? Only be able to watch anime or only be able to watch live-action movies?",
    "dbu": "What would you rather? Be able to speak to ghosts or speak to aliens?",
    "dbv": "What would you rather? Have a permanent 200ms lag in real life or have low-resolution vision?",
    "dbw": "What would you rather? Be a master of all instruments or a master of all languages?",
    "dbx": "What would you rather? Have to sleep in a coffin or have to sleep in a hammock?",
    "dby": "Would you rather? Only be able to communicate through emojis or only be able to communicate through 2012-era memes?",
    "dbz": "Would you rather? Have a life-sized statue of yourself in your front yard or have your face on a local billboard?",
    "dca": "Would you rather? Be a legendary hero who dies young or a mediocre person who lives to 150?",
    "dcb": "Would you rather? Have the ability to change your height or the ability to change your hair color at will?",
    "dcc": "Would you rather? Live in a world where everyone knows your thoughts or a world where you can't speak?",
    "dcd": "Would you rather? Be a master at every video game but suck at sports, or be a pro athlete but suck at games?",
    "dce": "Would you rather? Have a flying carpet or a submarine that can go anywhere?",
    "dcf": "Would you rather? Only eat breakfast foods for every meal or only eat dinner foods for every meal?",
    "dcg": "Would you rather? Be able to see through walls or be able to hear through any door?"
}

GamingAndInternet = {
    "eaa": "What is the first username you ever used, and why was it so cringe?",
    "eab": "If you could live inside one game world for a week, but you might actually die, would you do it? Which game?",
    "eac": "What is the most 'toxic' gamer moment you've witnessed (or been part of)?",
    "ead": "If you could delete one social media platform forever, which one would it be?",
    "eae": "Which video game character do you relate to the most?",
    "eaf": "What is an unpopular opinion you have about a 'critically acclaimed' game?",
    "eag": "What is your most cherished 'gaming' memory from your childhood?",
    "eah": "If you were an NPC in an RPG, what would your 'quest' be for the player?",
    "eai": "What is the most hours you've ever put into a single game?",
    "eaj": "Steam, Epic, or Console—which one is your primary home and why?",
    "eak": "What's the most legendary 'clutch' or 'fail' you've ever clipped?",
    "eal": "If you could bring one item from a video game into real life, what would it be?",
    "eam": "What is a dead game/community you wish would come back to life?",
    "ean": "What is the best OST (soundtrack) in gaming history?",
    "eao": "If you were a streamer, what would be your 'gimmick'?"
}

deck_map = {
    "General Questions": GeneralQuestions,
    "Press the Button": PressTheButton,
    "Reflection Questions": ReflectionQuestions,
    "Would You Rather?": WouldYouRather,
    "Gaming and Internet": GamingAndInternet
}

def get_random_question():
    if len(used_questions) >= len(WouldYouRather) + len(ReflectionQuestions) + len(PressTheButton) + len(GeneralQuestions) + len(GamingAndInternet):
        used_questions.clear()
    while True:
        deck = random.choice(list(deck_map.keys()))
        questions = deck_map[deck]
        question_key = random.choice(list(questions.keys()))
        if question_key not in used_questions:
            used_questions.append(question_key)
            break
    question = questions[question_key]
    return deck, question, question_key